trigger:
- main

pool: Default

variables:
  solution: '**/AppBL/*.sln'
  buildPlatform: 'Any Cpu'
  buildConfiguration: 'Release'
  solution_main: 'GACDRest'
  solution_root: 'AppBL'



steps:

# Restore, Build, Test, Deploy
  - task: DotNetCoreCLI@2
    displayName: Restore Project Dependencies
    inputs:
      command: 'restore'
      projects: '$(solution)'
      feedsToUse: 'select'
  
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'sonar-cloud-kwik'
      organization: '210503-reston-net'
      scannerMode: 'MSBuild'
      projectKey: '210503-Reston-NET_GACD-P2'
      projectName: 'GACD-P2'
      extraProperties: 'sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/**/coverage.opencover.xml'

  - task: DotNetCoreCLI@2
    displayName: Build Projects
    inputs:
      command: 'build'
      projects: '$(solution)'
    
#V2
  - task: DotNetCoreCLI@2
    displayName: 'Run unit tests - $(buildConfiguration)'
    inputs:
      command: 'test'
      arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true "/p:CoverletOutputFormat=\"opencover,Cobertura\"" /p:Exclude=\"[Data.Migrations.*]*\"'
      publishTestResults: true
      projects: '$(solution)'

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage report'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml'
      reportDirectory: '$(Build.SourcesDirectory)/App/Tests/' 

  - task: SonarCloudAnalyze@1
    displayName: Run Code Analysis
  - task: SonarCloudPublish@1
    displayName: Publish Code Analysis
  
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: 'publish'
      publishWebProjects: false
      zipAfterPublish: true
      projects: '**/AppBL/GACDRest/*.csproj'

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'kwikcode-azure'
      appType: 'webAppLinux'
      WebAppName: 'KwickKoderRest'
      packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
      RuntimeStack: 'DOTNETCORE|5.0'

